FROM ubuntu:22.04

# install minimum reqs
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive && apt install -y software-properties-common sudo && add-apt-repository multiverse && apt update && export DEBIAN_FRONTEND=noninteractive && apt-get install -y --no-install-recommends pkg-config && apt-get -f -y install && dpkg --configure -a && apt-get clean all && apt -y autoremove

# install baseline x, vnc
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive && apt-get install -y linux-tools-common hwdata apt-utils software-properties-common && apt-get update -y && apt-get install -y git wget curl net-tools linux-tools-generic && apt-get clean all && apt -y autoremove
RUN export DEBIAN_FRONTEND=noninteractive && apt-get install -y novnc x11vnc  tightvncserver tigervnc-scraping-server novnc xvfb xterm firefox ssh-askpass-gnome && apt-get clean all && apt -y autoremove

# norights user, .vnc store
RUN adduser --disabled-password --gecos "" user
RUN cp /usr/share/novnc/vnc.html /usr/share/novnc/index.html && mkdir /root/.vnc

#copy run scripts
COPY run-minimum /root
RUN chmod 755 /root/run-minimum

# vnc settings
COPY xorg.conf /usr/share/X11/xorg.conf.d/
COPY passwd /root/.vnc/
COPY xstartup /root/.vnc/
RUN chmod 755 /root/.vnc/xstartup

EXPOSE 5900 6080
ENTRYPOINT /root/run-minimum
