FROM ubuntu:kinetic

# install minimum reqs
RUN apt update && export DEBIAN_FRONTEND=noninteractive && apt install -y software-properties-common sudo && add-apt-repository multiverse && apt update && export DEBIAN_FRONTEND=noninteractive && apt install -y --no-install-recommends pkg-config && apt -f -y install && dpkg --configure -a && apt clean all && apt -y autoremove

# install baseline x, vnc
RUN apt update && export DEBIAN_FRONTEND=noninteractive && apt-get install -y linux-tools-common hwdata apt-utils software-properties-common && apt-get update -y && apt install -y git wget curl net-tools linux-tools-generic && apt clean all && apt -y autoremove
RUN export DEBIAN_FRONTEND=noninteractive && apt install -y novnc x11vnc neofetch tightvncserver tigervnc-scraping-server novnc xrdp xvfb xterm ssh-askpass-gnome && apt-get clean all && apt -y autoremove

# get chrome-repo in apt
RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
RUN apt update && apt install -y google-chrome-stable && apt clean all  && apt -y autoremove

# norights user, .vnc store
RUN adduser --disabled-password --gecos "" user
RUN cp /usr/share/novnc/vnc.html /usr/share/novnc/index.html && mkdir /root/.vnc

#copy run scripts
COPY run-minimum /root
RUN chmod 755 /root/run-minimum

# vnc settings
COPY xorg.conf /usr/share/X11/xorg.conf.d/
COPY passwd /root/.vnc/
COPY xstartup /root/.vnc/
RUN chmod 755 /root/.vnc/xstartup

EXPOSE 3389 5900 6080
ENTRYPOINT /root/run-minimum
